### ISSUE TITLE
889: Global Change from SAM to SAM.gov (on cloud.gov version)

### ISSUE THREAD

**Issue by vickimcfadden** [GSA/smartpay-website#131]
In the [889 usability testing](https://docs.google.com/presentation/d/1h0isq2BNZ-AY3yqe2EowCtk_y1riiWYToEfD0NQsQDs/edit#slide=id.g1e18e72db15_1_9) users noted that the acronym `SAM` was confusing to them and they were more familiar with `UEI`.

Both the results page and the generated PDF. 

**Acceptance Criteria:**

- [ ] On the 889 homepage, add (UEI) after SAM.gov Unique Entity ID (above the search box)
- [ ] Make a global change from "SAM" to "SAM.gov," including the PDF.  **NOTE** PDF also includes "sam.gov," please capitalize to "SAM.gov"
- [ ] Change "SAM" to "SAM.gov UEI" in the 889 tool in the results tabs
![Image](https://github.com/GSA/smartpay-website/assets/116583391/4c5896e3-a368-4ba7-9ed4-4c4c35615bef)

**Comment by vickimcfadden** [comment]
For consideration @A-L33 @JessicaMarine1

**Comment by A-L33** [comment]
That makes sense.  Unless @rebekahperillo has any concerns and it's not a high level of effort for @mark-meyer or @jfredrickson5, this makes sense.

**Comment by A-L33** [comment]
That works for me.  SAM UEI or UEI is good.

**Comment by rebekahperillo** [comment]
@mark-meyer Hi, looks good overall, but saw one sam.gov reference at the bottom of the downloadable document. Do you think we need to update it to SAM.gov?

[Record of Section 889 Representations - ABC AUTO PARTS, LTD.-3.pdf](https://github.com/GSA/smartpay-website/files/12260404/Record.of.Section.889.Representations.-.ABC.AUTO.PARTS.LTD.-3.pdf)

**Comment by mark-meyer** [comment]
@rebekahperillo Since this is a url in a link, I think we should double check with @brentryanjohnson. Lower case seems right for a url, but maybe we should keep the link pointing to https://sam.gov, but change the linked text so it looks like:  [SAM.gov](https://sam.gov) — either way it's a simple change.

**Comment by brentryanjohnson** [comment]
Yeah, I think we can omit the colon and use SAM.gov as link text.

**Comment by mark-meyer** [comment]
Ugh, sorry @brentryanjohnson and @rebekahperillo  this may not be possible without a lot of work. The PDF library we are using doesn't [handle anchors correctly](https://github.com/parallax/jsPDF/issues/3146). We are able to get a clickable link because the PDF reader recognizes the url and adds the link for us. If we don't include the full `https://sam.gov` in the text, the links don't work in acrobat. So it seems like the choices are `https://sam.gov` or `https://SAM.gov`, but not `SAM.gov` with a functioning link.

**Comment by brentryanjohnson** [comment]
Got it. Let's go with https://SAM.gov in accordance with their style guide 👍.

**Comment by mark-meyer** [comment]
@brentryanjohnson and @rebekahperillo this change is up on staging now.

**Comment by rebekahperillo** [comment]
Moving over to "DONE". Thanks to @mark-meyer and @brentryanjohnson for helping here!
