### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#140]
Path: 404/
File name: 
Design: [404 Page](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1374%3A38588&t=NB2CPqpZgPZBO4xz-1)
Template: [404 Template](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1452%3A41748&t=NB2CPqpZgPZBO4xz-1)
_______________

**Comment by mark-meyer** [comment]
@klohman we should now have a 404 page! 

Best way to test is by appending gibberish to the url like:
https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/gglkjkjg/

Because of the way we are deployed without a real domain, if you remove paths from the url eventually you will get back to the server's 404 (like https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa), but this shouldn't be an issue once we are really running.

**Comment by klohman** [comment]
@rebekahperillo Ready for review.

**Comment by rebekahperillo** [comment]
Beautiful 404 page. :) Tested and approved. Moving to "Done".
