### ISSUE TITLE
Mobile Review

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#248]
As a user, I want to be able to easily navigate the program site on my mobile device.

**Acceptance Criteria:**

- [x] Do UX review on mobile
- [x] Log issues

**Comment by klohman** [comment]
# Review comments 

## Logo 
* Logo is overlapping the page content and needs to be scaled down to fit in the menu bar on mobile 
![image](https://github.com/GSA/smartpay-website/assets/18366192/44436729-543a-4c20-8e35-e4ef18c1a487)

## Button alignment 
* Text in button should be centered vertically. You notice it more on the "Benefits" button. 
![image](https://github.com/GSA/smartpay-website/assets/18366192/ade75d15-5dda-499c-a7ba-d18d4ee39862)

## Menu 
* Strategic Payment Solutions is very cramped. Is it possible to adjust padding? 
![image](https://github.com/GSA/smartpay-website/assets/18366192/1e7894eb-ea46-42f6-9166-51e2f5680442)

## Smart Bulletins table 
* There is a weird double border on the Title column in this table. 
![image](https://github.com/GSA/smartpay-website/assets/18366192/bb11eee8-a371-4706-996f-9f350f9b5163)


@brentryanjohnson Do you have any other comments to add?

**Comment by brentryanjohnson** [comment]
I haven't yet done a thorough review, but I noticed a few things while I was getting caught up this week.

## Global

### Logo

The SmartPay logo doesn't sufficiently resize to its container on smaller viewports, causing it to collide with `div`s both above and below it.

#### Content page
![Screenshot with GSA SmartPay logo leaking above and blow ](https://github.com/GSA/smartpay-website/assets/32855580/3027849e-55cb-4426-83b4-2a4372cdf004)

#### Homepage
![logo-2](https://github.com/GSA/smartpay-website/assets/32855580/6cc68b2d-6465-4a8a-be97-212b1a803d1b)

## Images

### Image resolution

Card images in particular are pixelated and blurry on mobile. I suspect this might be due to the retina display. We might want to consider bumping the resolution to 2x the rendered size to fix this problem on retina display.

![card-image-res-2](https://github.com/GSA/smartpay-website/assets/32855580/9278292a-8682-42b2-bfe5-22863228896b)
![card-image-res](https://github.com/GSA/smartpay-website/assets/32855580/56e07c50-01d9-4211-b0b7-747cd80c40e1)

## Tables

### Table borders

I'm not sure what's causing this, but the table borders in certain instances have a double border under certain cells. For example, on Smart Bulletins, the table border is doubled only in the table column.

![line-spacing](https://github.com/GSA/smartpay-website/assets/32855580/64e077b2-6877-4360-b464-7702750bcc19)

## Margin, padding, line height

These are relatively minor, but there are some spacing issues to clean up if we have time. 

### Tight space on image wrap
![image](https://github.com/GSA/smartpay-website/assets/32855580/110f5f83-102b-4611-a151-3eb89e00f8b0)

### Overly generous line height on intro text

![image](https://github.com/GSA/smartpay-website/assets/32855580/0d90b5de-9497-428c-bb8b-a027a536fae3)

**Comment by weiwang-gsa** [comment]
@klohman @brentryanjohnson this is ready for design review: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/preview/gsa/smartpay-website/staging/

**Comment by klohman** [comment]
@weiwang-gsa The purchase card image is not displaying like the others when I view the homepage. 

![image](https://github.com/GSA/smartpay-website/assets/18366192/d9701d0d-ea4a-4b1b-913b-15cc3cc1eccf)

**Comment by weiwang-gsa** [comment]
@klohman code changes are merged into staging, can be reviewed here: https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/preview/gsa/smartpay-website/staging/

**Comment by klohman** [comment]
@rebekahperillo @A-L33 Ready for QA

**Comment by rebekahperillo** [comment]
@klohman Wow, looking sharp on mobile! Moving to "DONE". Thank you!
