### ISSUE TITLE
Website Image Sizes

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#275]
A user reported slow loading for the hero image on the home page.  Upon review, the image was larger than it needed to be.  It will benefit performance to review image sizes on the website and reduce/compress as needed.

**Acceptance Criteria:**
- [ ] Conduct an inventory of images on the site
- [ ] Verify that images are all reasonably sized (no standard sizing; "small but good")
- [ ] Compress any images that are larger than required

**Comment by JessicaMarine1** [comment]
Ryan already fixed the homepage hero image.

**Comment by brentryanjohnson** [comment]
I reviewed the remaining images on the site.

It is true that in some instances, the source image is `1000px` and the rendered size (on some viewports) is a small as `200px`. But on other viewports, such as card images on Business Lines at `630px` wide viewport, the image is rendered at `500px`.

![Screenshot of red card image showing the web inspector with intrinsic size of 1017 by 642 and rendered size of 530 by 335](https://github.com/GSA/smartpay-website/assets/32855580/87194b7f-029b-4436-8cb8-04fd61108172)

Because of the pixel density of some displays (namely "retina" displays), the source image should be twice the resolution of the rendered size on the page. At `530px`, a source image of `1017px` is barely adequate to avoid artifacts on a high resolution screen.

The card images, in particular, are PNG format, and thus more difficult to compress compared to JPEG. Even so, the PNG card images are only 159KB, which is relatively small for image file size.

With the hero image compressed, I think we can move this issue to done.

**Comment by JessicaMarine1** [comment]
@A-L33 @rebekahperillo please see Ryan's note above.

**Comment by A-L33** [comment]
Done!
