### ISSUE TITLE
Curly quotes

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#316]
During our content updating session with Lora, when she manually typed an apostrophe, it rendered as a straight apostrophe; not curly. Is there a plug-in that will automatically make all apostrophes curly?

**Comment by brentryanjohnson** [comment]
@mark-meyer @weiwang-gsa We noticed this with content in the front matter `intro` key, so that may be part of the issue (see `agency‘s` versus `merchant's` on the [logos page](https://demo.smartpay.gsa.gov/about/logos/)).

It looks like the `remark-smartypants` is default in Astro, but apparently [there are issues](https://github.com/withastro/astro/issues/4448) with parsing `mdx`?

**Comment by mark-meyer** [comment]
Hmm. It looks like that issue is related to quotes around links like "[some link](http://example.com)" since the link is processed separately from the surrounding unlinked text (in this case the quotes).

I did a couple tests and it looks like smartypants is working for mdx (other than the above edge case).

The case in this ticket, however, is different. The front-matter is not processed with the markdown, but added later in the template. So if we want to process this text to take care of things like smart quotes, we will need to do it differently.  🤔

**Comment by mark-meyer** [comment]
@brentryanjohnson this is merged in and running.

**Comment by JessicaMarine1** [comment]
@A-L33 @rebekahperillo ready for review. You'll see that the word `merchant's` on the logo page intro now has the curly apostrophe.

**Comment by rebekahperillo** [comment]
Moving to DONE. Thank you!
