### ISSUE TITLE
Customer Support

### ISSUE THREAD

**Issue by A-L33** [GSA/smartpay-website#56]
Path: contact/
File name: 
Design: [Contact > Customer Support](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1374%3A37081&t=NB2CPqpZgPZBO4xz-1)
Template: [Sidebar Template](https://www.figma.com/file/bgNCEcglYMCDtEEBys04cx/SmartPay?type=design&node-id=1452-41800&t=ZdXxtCQnJUFtcq4C-4)
_______________ 

- Customer service information: https://docs.google.com/document/d/1Mf6RaUjgzj_Ou1CWN2Stc65YNIlJdKxmrjmd7HvAsqs/edit.

**Comment by johnbeallgsa** [comment]
@brentryanjohnson ready for review

**Comment by brentryanjohnson** [comment]
✅  Reviewed. This one and #57 are effectively redundant now.

**Comment by JessicaMarine1** [comment]
Closed #57

**Comment by JessicaMarine1** [comment]
@klohman on this design in Figma, can you delete Donna Rankin and change Nichole Ammon's title to: Team Lead, Acquisition Support

**Comment by mark-meyer** [comment]
@klohman this is ready for a design review. Per the discussion today, this should be the page you get when you use the "contact" link in the top navigation.

https://federalist-ab31a10d-375d-4040-9324-1ae94e8a36b9.sites.pages.cloud.gov/site/gsa/smartpay-website/contact/

**Comment by JessicaMarine1** [comment]
Closed #142 as no longer needed.

**Comment by klohman** [comment]
@rebekahperillo Ready for QA!

**Comment by rebekahperillo** [comment]
Hi! 

Please see my feedback below. We may need to talk this through - just let me know!

Under "Center for Charge Card Management (CCCM) Contact Information", there is a spacing issue with Sarah Smith's information (Sarah Smith Business Management Specialist is on one line). If that can be fixed, that would be great. And, since that is being fixed, let's update the following titles:

Rebekah Knouse Perillo
Lead Business Management Specialist
301-938-5257
[rebekah.knouse@gsa.gov](mailto:rebekah.knouse@gsa.gov)

Joline McDonald
Lead Business Management Specialist
703-822-1304
[joline.mcdonald@gsa.gov](mailto:joline.mcdonald@gsa.gov)

Nichole Ammon
Supervisory Contracting Officer
470-449-0996
[nichole.ammon@gsa.gov](mailto:nichole.ammon@gsa.gov)

Also, the flow for the "Contact" page is confusing for me.

"Customer Support" and "CCCM Contact Information" work.

Under "Bank Contact Information", I think we should have:

Card/account holders, please contact your agency’s issuing bank directly about: 
Specific account issues.
How to use the bank’s online account access website.
Changes to address or personal information change.
Payment.
Delinquency.
Confusion about your bill.
Disputed transactions.

The GSA SmartPay® team does not have the ability to look up any account information.


Then, nested under "Bank Contact Information" have the "GSA SmartPay 3® Contractor Banks" information (eliminating the "Agency Bank Information" heading).

GSA SmartPay 3® Contractor Banks
For specific account questions, please see the contact information for the banks below.

Citibank
800-790-7206 (within United States)
904-954-7850 (collect calls from outside United States)
[Citibank Online Account Access](https://home.cards.citidirect.com/CommercialCard/Cards.html) (self register, commercial site).

U.S. Bank
888-994-6722 (within United States) Note: To speak with a live person, do not press any buttons.
701-461-2232 (collect calls from outside United States)
[U.S. Bank Online Account Access](https://access.usbank.com/cpsApp1/index.jsp) (self register, commercial site).

WEX
866-939-4472

To learn which bank/brand provides your agency’s GSA SmartPay 3 services, please email [gsa_smartpay@gsa.gov](mailto:gsa_smartpay@gsa.gov).

If card/account holders require assistance with contacting the bank or with agency-specific charge card/account related issues, please reach out to your agency’s program coordinator (A/OPC).

**Comment by JessicaMarine1** [comment]
@rebekahperillo this is ready for your re-review.

**Comment by rebekahperillo** [comment]
Moving to "Done"! Thank you!
